image: ruby:2.6.0

stages:
  - lint
  - test

cache:
  paths:
    - vendor/ruby

rubocop:
  stage: lint
  before_script:
    - gem install rubocop -v 0.72.0
  script:
    - rubocop
  except:
    - schedules

bundler-audit:
  stage: lint
  before_script:
    - gem install bundler -v 1.17.3
    - bundle install --path vendor
    - gem install bundler-audit
  script:
    - bundle audit

rspec:
  stage: test
  before_script:
    - gem install bundler -v 1.17.3
    - bundle install --path vendor
  script:
    - bundle exec rspec
  except:
    - schedules
