image: ruby:2.6.0

stages:
  - lint
  - test
  - analysis

cache:
  paths:
    - vendor/ruby

rubocop:
  stage: lint
  before_script:
    - gem install rubocop -v 0.71.0
  script:
    - rubocop
  except:
    - schedules

bundler-audit:
  stage: lint
  before_script:
    - gem install bundler -v 1.17.3
    - bundle install --path vendor
    - gem install bundler-audit
  script:
    - bundle audit
  allow_failure: true

rspec:
  stage: test
  before_script:
    - gem install bundler -v 1.17.3
    - bundle install --path vendor
  script:
    - bundle exec rspec
  except:
    - schedules

sonarqube:
  stage: analysis
  image: registry.5xruby.tw/docker/sonar-scanner:4.0.0
  script:
    - sonar-scanner
      -D"sonar.projectKey=5xruby-bankai"
      -D"sonar.projectBaseDir=${CI_PROJECT_DIR}"
      -D"sonar.host.url=https://sonar.5xruby.tw"
      -D"sonar.login=${SONARQUBE_TOKEN}"
      -D"sonar.projectVersion=${CI_COMMIT_SHORT_SHA}"
