PreCommit:
  AuthorName:
    enabled: false
  RuboCop:
    enabled: true
    on_warn: fail # Treat all warnings as failures
  TrailingWhitespace:
    enabled: true
    exclude:
      - '.licenses/**/*'

PrePush:
  BundleAudit:
    enabled: true
  BundleOutdated:
    enabled: true

PostCheckout:
  ALL: # Special hook name that customizes all hooks of this type
    quiet: true # Change all post-checkout hooks to only display output on failure
  IndexTags:
    enabled: true # Generate a tags file with `ctags` each time HEAD changes
