require 'rb5/version'
require 'rb5/generator'
require 'rb5/generators/testing_generator'
require 'rb5/generators/ci_generator'
require 'rb5/generators/json_generator'
require 'rb5/generators/lint_generator'
require 'rb5/builder'
