#!/usr/bin/env ruby
# frozen_string_literal: true

# Prepend, so running this file straight out of a checkout uses that checkout
# rather than whichever bankai gem happens to be installed.
$LOAD_PATH.unshift(File.expand_path('../lib', __dir__))

require 'bankai'

if ARGV.empty?
  puts 'Please provide a path for the new application'
  puts
  puts 'See --help for more info'
  exit 0
elsif ['-v', '--version'].include? ARGV[0]
  puts Bankai::VERSION
  exit 0
end

templates_root = File.expand_path(
  File.join('..', 'templates'),
  File.dirname(__FILE__)
)
Bankai::Generator.source_root templates_root
Bankai::Generator.source_paths << Rails::Generators::AppGenerator.source_root
Bankai::Generator.source_paths << templates_root

Bankai::Generator.start
